FROM postgres:14.3

WORKDIR /docker-entrypoint-initdb.d

COPY ../database-scripts/init.sql /docker-entrypoint-initdb.d/init.sql
#USER postgres
#RUN psql -U postgres -f /docker-entrypoint-initdb.d/init.sql
ENV POSTGRES_HOST_AUTH_METHOD=trust
EXPOSE 8050
